name: Gildie
version: '1.2'
main: pl.gildie.GildiePlugin
api-version: '1.20'
author: Gildie
description: Gildie z terenem, ochrona, regeneracja TNT, dom, baza wypadowa, WP
softdepend: [ReiMinimap]
commands:
  g:
    description: Komendy gildii
    usage: /g <zaloz|zapros|dom|ubw|bw|...>
    aliases: [gildia, guild]
